apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prefix }}app-pvc
  namespace: {{ .Values.prefix }}
  labels:
    app: {{ .Values.prefix }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: {{ .Values.prefix }}app-pv